### ISSUE TITLE
Issue with pre-trained question-type identification and question-focus recognition models

### ISSUE THREAD

**Issue by jatinS-dev** [shwetanlp/CHQ-Summ#6]
@shwetanlp 
### Steps to reproduce the issue
1.Complete the step 1 & 2 given in the readme.md of the repository
2. Download the pre-trained model in the current directory
3. Run the command `python main.py --train_mode rl --trained_model_path /path/to/the/fine-tuned/prophetnet/model`

### Expected result
It should train the model

### Actual result
```
python main.py --train_mode rl --trained_model_path /home/sosukeaizen/Desktop/saved_model/prophetnet-meqsum-model

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    from reward.compute_question_type_reward import get_question_type_reward
  File "/home/sosukeaizen/Desktop/task/CHQ-Summ/reward/compute_question_type_reward.py", line 67, in <module>
    type_model.load_state_dict(torch.load('type_model/epochs-7'))
  File "/home/sosukeaizen/.local/lib/python3.8/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/sosukeaizen/.local/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/sosukeaizen/.local/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: 'type_model/epochs-7'

```
### System information (as much as possible)

Ubuntu 20.04.5 LTS

### Additional comments
It is not able to identify `type_model/epochs-7'`

**Comment by jatinS-dev** [comment]
`solved!`

we can solve this by making `type_model` directory and adding `epochs-7` zip file over there.
